line-length = 120

[lint]
preview = true

select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "D",
]

# These have compat issues with other rules, the last one is about exceptions and pisses me off
ignore = ["D203", "D213", "E722"]